# -- Main Menu --
# The main menu is displayed in the header at the top of the page.
# Acceptable parameters are name, pageRef, page, url, title, weight.
# 
# The simplest menu configuration is to provide:
#   name = The name to be displayed for this menu link
#   pageRef = The identifier of the page or section to link to
#
# By default the menu is ordered alphabetically. This can be
# overridden by providing a weight value. The menu will then be
# ordered by weight from lowest to highest.

[[main]]
 name = "容器和k8s"
 pageRef = "container-and-k8s"
 weight = 3

[[main]]
 name = "杂谈"
 pageRef = "essay"
 weight = 4

[[main]]
 name = "编程语言"
 weight = 5

[[main]]
 name = "Go"
 parent = "编程语言"
 pageRef = "go"
 weight = 10

[[main]]
 name = "Python"
 parent = "编程语言"
 pageRef = "python"
 weight = 10

[[main]]
 name = "TypeScript"
 parent = "编程语言"
 pageRef = "typescript"
 weight = 10

# Github
[[main]]
  name = "GitHub"
  url = "https://github.com/loveRyujin"
  weight = 90
  pre = "github"  

# RSS Feed
[[main]]
  name = "RSS"
  url = "/index.xml"
  weight = 100
  pre = "rss"  

#[[main]]
#  name = "example sub-menu 2"
#  parent = "Parent"
#  pageRef = "posts"
#  weight = 20

#[[subnavigation]]
#  name = "An interesting topic"
#  pageRef = "tags/interesting-topic"
#  weight = 10

#[[subnavigation]]
#  name = "My Awesome Category"
#  pre = "github"
#  pageRef = "categories/awesome"
#  weight = 20

#[[main]]
#  name = "Categories"
#  pageRef = "categories"
#  weight = 20

#[[main]]
#  name = "Tags"
#  pageRef = "tags"
#  weight = 30


# -- Footer Menu --
# The footer menu is displayed at the bottom of the page, just before
# the copyright notice. Configure as per the main menu above.


# [[footer]]
#   name = "Tags"
#   pageRef = "tags"
#   weight = 10

# [[footer]]
#   name = "Categories"
#   pageRef = "categories"
#   weight = 20
